"""
GLM-4.5 MoE Accuracy Test: Compare NeuronX model output against HuggingFace model.

The test passes if generated token sequences match exactly (greedy, top_k=1).

Usage:
    python test_glm4_moe_accuracy.py
    python test_glm4_moe_accuracy.py --model-path /path/to/model --traced-model-path /path/to/traced
"""

import argparse
import sys
import torch
from transformers import AutoTokenizer, Glm4MoeForCausalLM, GenerationConfig

from neuronx_distributed_inference.models.config import (
    MoENeuronConfig,
    OnDeviceSamplingConfig,
)
from neuronx_distributed_inference.models.glm4_moe.modeling_glm4_moe import (
    Glm4MoeInferenceConfig,
    NeuronGlm4MoeForCausalLM,
)
from neuronx_distributed_inference.utils.hf_adapter import (
    HuggingFaceGenerationAdapter,
    load_pretrained_config,
)

MODEL_PATH = "glm4_moe_tiny_random"
TRACED_MODEL_PATH = "glm4_moe_tiny_random_traced"

torch.manual_seed(0)

MAX_NEW_TOKENS = 10
SEQ_LEN = 64
TP_DEGREE = 2


# ---------------------------------------------------------------------------
# HuggingFace reference output
# ---------------------------------------------------------------------------


def run_hf_model(model_path: str, input_ids: torch.Tensor, max_new_tokens: int):
    """Run the HF model on CPU and return generated token ids."""
    print("\n[HF] Loading HuggingFace GLM-4.5 MoE model on CPU...")
    hf_model = Glm4MoeForCausalLM.from_pretrained(
        model_path,
        torch_dtype=torch.float32,  # CPU inference in FP32 for accuracy
    )
    hf_model.eval()

    gen_config = GenerationConfig(
        max_new_tokens=max_new_tokens,
        do_sample=False,
        temperature=1.0,
    )

    print(f"[HF] Running generation with input_ids shape: {input_ids.shape}")
    with torch.no_grad():
        hf_output = hf_model.generate(
            input_ids,
            generation_config=gen_config,
        )

    print(f"[HF] Output token ids: {hf_output}")
    return hf_output


# ---------------------------------------------------------------------------
# NeuronX model output
# ---------------------------------------------------------------------------


def run_neuron_model(
    traced_model_path: str,
    model_path: str,
    input_ids: torch.Tensor,
    max_new_tokens: int,
):
    """Load compiled Neuron model and return generated token ids."""
    print("\n[Neuron] Loading compiled GLM-4.5 MoE Neuron model...")
    neuron_model = NeuronGlm4MoeForCausalLM(traced_model_path)
    neuron_model.load(traced_model_path)

    attention_mask = torch.ones_like(input_ids)

    gen_config = GenerationConfig(
        max_new_tokens=max_new_tokens,
        do_sample=False,
        top_k=1,
    )

    generation_model = HuggingFaceGenerationAdapter(neuron_model)

    print(f"[Neuron] Running generation with input_ids shape: {input_ids.shape}")
    neuron_output = generation_model.generate(
        input_ids,
        generation_config=gen_config,
        attention_mask=attention_mask,
        max_length=neuron_model.config.neuron_config.max_length,
    )

    print(f"[Neuron] Output token ids: {neuron_output}")
    return neuron_output


# ---------------------------------------------------------------------------
# Comparison
# ---------------------------------------------------------------------------


def compare_outputs(
    hf_output: torch.Tensor, neuron_output: torch.Tensor, max_new_tokens: int
):
    """Compare new tokens generated by HF and Neuron models."""
    # Both outputs include the original prompt. Slice the new tokens.
    prompt_len = hf_output.shape[-1] - max_new_tokens
    hf_new_tokens = hf_output[0, prompt_len:]
    neuron_new_tokens = neuron_output[0, prompt_len : prompt_len + max_new_tokens]

    print(f"\n[Compare] HF new tokens:     {hf_new_tokens.tolist()}")
    print(f"[Compare] Neuron new tokens:  {neuron_new_tokens.tolist()}")

    match = torch.equal(hf_new_tokens, neuron_new_tokens)
    if match:
        print("\n✅ PASS: Neuron output matches HuggingFace output exactly!")
    else:
        # Show token-level diff
        n = min(len(hf_new_tokens), len(neuron_new_tokens))
        diffs = [
            f"pos {i}: HF={hf_new_tokens[i].item()}, Neuron={neuron_new_tokens[i].item()}"
            for i in range(n)
            if hf_new_tokens[i] != neuron_new_tokens[i]
        ]
        print(f"\n❌ FAIL: Output mismatch at {len(diffs)} position(s):")
        for d in diffs[:10]:
            print(f"  {d}")

    return match


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------


def main():
    parser = argparse.ArgumentParser(description="GLM-4.5 MoE accuracy test")
    parser.add_argument("--model-path", default=MODEL_PATH, help="Path to HF model")
    parser.add_argument(
        "--traced-model-path",
        default=TRACED_MODEL_PATH,
        help="Path to compiled Neuron model",
    )
    parser.add_argument(
        "--max-new-tokens",
        type=int,
        default=MAX_NEW_TOKENS,
        help="Number of new tokens to generate",
    )
    args = parser.parse_args()

    print("=" * 60)
    print("GLM-4.5 MoE Accuracy Test")
    print("=" * 60)

    # Use fixed dummy input ids (no tokenizer needed for tiny random model)
    input_ids = torch.tensor([[1, 2, 3, 4, 5]], dtype=torch.long)
    print(f"Input token ids: {input_ids}")

    # Run HF model
    hf_output = run_hf_model(args.model_path, input_ids, args.max_new_tokens)

    # Run Neuron model (requires compiled model in traced_model_path)
    neuron_output = run_neuron_model(
        args.traced_model_path, args.model_path, input_ids, args.max_new_tokens
    )

    # Compare
    passed = compare_outputs(hf_output, neuron_output, args.max_new_tokens)

    print("\n" + "=" * 60)
    if passed:
        print("RESULT: PASS ✅")
        sys.exit(0)
    else:
        print("RESULT: FAIL ❌")
        print(
            "NOTE: Random-weight model accuracy may vary due to numerical differences"
        )
        print("      between CPU float32 (HF) and bfloat16 Neuron execution.")
        sys.exit(1)


if __name__ == "__main__":
    main()
