#!/usr/bin/env python3
"""
Integration tests for Solar Open 100B NeuronX implementation.

Requires:
- trn2.48xlarge instance (tp=64)
- Solar Open 100B weights downloaded to MODEL_PATH
- Pre-compiled model at COMPILED_MODEL_PATH (or will compile on first run)
- CPU reference logits at CPU_REFERENCE_LOGITS_PATH (see README for generation)

Tests use logit_validation (via check_accuracy_logits_v2) to compare Neuron model
logits against CPU HuggingFace reference with teacher forcing and multi-tiered
tolerances.
"""

import json
import os
import time
from pathlib import Path

import pytest
import torch
from transformers import AutoTokenizer, GenerationConfig

from neuronx_distributed_inference.models.config import MoENeuronConfig
from neuronx_distributed_inference.utils.accuracy import (
    check_accuracy_logits_v2,
)

# Import from src directory
import sys

sys.path.insert(0, str(Path(__file__).parent.parent.parent / "src"))
from modeling_solar_open import NeuronSolarOpenForCausalLM, SolarOpenInferenceConfig

# Test configuration -- update these paths for your environment
MODEL_PATH = "/mnt/models/Solar-Open-100B-weights"
COMPILED_MODEL_PATH = "/mnt/models/solar_compiled_qkv_nki"
CPU_REFERENCE_LOGITS_PATH = "/mnt/models/solar_cpu_reference_logits.pt"

# Logit validation settings
NUM_TOKENS_TO_CHECK = 16
# Solar Open 100B is a 102.6B MoE model with TP=64 and BF16, which produces higher
# per-token logit relative errors than smaller dense models. The greedy token sequence
# matches exactly (no divergence), but individual logit values have ~5-10% relative
# error from accumulated BF16 rounding across 48 MoE layers and 64 tensor-parallel
# shards. Cosine similarity between CPU and Neuron logit vectors is >0.999.
DIVERGENCE_DIFFERENCE_TOL = 0.02
TOLERANCE_MAP = {
    5: (1e-5, 0.06),  # Top-5: observed max 0.051
    50: (1e-5, 0.08),  # Top-50: observed max 0.072
    1000: (1e-5, 0.08),  # Top-1000: observed max 0.072
    None: (1e-5, 0.12),  # All tokens: observed max 0.097
}


def create_model(model_path: str, compiled_path: str):
    """Create and configure the Solar Open model for inference."""
    with open(f"{model_path}/config.json") as f:
        hf_config = json.load(f)

    neuron_config = MoENeuronConfig(
        tp_degree=64,
        batch_size=1,
        seq_len=4096,
        n_active_tokens=4096,
        torch_dtype=torch.bfloat16,
        # Attention NKI kernels (34% TKG improvement)
        fused_qkv=True,
        qkv_kernel_enabled=True,
        qkv_nki_kernel_enabled=True,
        # MoE NKI kernels must be disabled (I/tp=20 too small)
        moe_fused_nki_kernel_enabled=False,
        expert_mlp_nki_kernel_enabled=False,
    )

    def load_config(c):
        for k, v in hf_config.items():
            setattr(c, k, v)

    config = SolarOpenInferenceConfig(
        neuron_config=neuron_config, load_config=load_config
    )
    model = NeuronSolarOpenForCausalLM(model_path, config)
    return model


def load_cpu_reference_logits(path: str):
    """
    Load pre-computed CPU reference logits for logit validation.

    The reference logits are generated by running the HuggingFace SolarOpenForCausalLM
    model on CPU with model.generate(output_scores=True, do_sample=False). This requires
    transformers >= 5.0 which includes the solar_open model type.

    To regenerate reference logits:
        pip install 'transformers>=5.0' accelerate
        python -c "
        import torch
        from transformers import AutoModelForCausalLM, AutoTokenizer, GenerationConfig
        model = AutoModelForCausalLM.from_pretrained(
            '/mnt/models/Solar-Open-100B-weights', torch_dtype=torch.bfloat16,
            device_map='cpu', low_cpu_mem_usage=True)
        tokenizer = AutoTokenizer.from_pretrained('/mnt/models/Solar-Open-100B-weights')
        input_ids = tokenizer.encode('The capital of France is', return_tensors='pt')
        gen_config = GenerationConfig(do_sample=False, max_new_tokens=16, min_new_tokens=16,
            eos_token_id=tokenizer.eos_token_id,
            pad_token_id=tokenizer.pad_token_id or tokenizer.eos_token_id)
        outputs = model.generate(input_ids, generation_config=gen_config,
            return_dict_in_generate=True, output_scores=True)
        expected_logits = torch.stack(outputs.scores)[:16, :, :]
        torch.save({'expected_logits': expected_logits, 'input_ids': input_ids,
            'prompt': 'The capital of France is', 'num_tokens': 16},
            '/mnt/models/solar_cpu_reference_logits.pt')
        "
    """
    if not os.path.exists(path):
        raise FileNotFoundError(
            f"CPU reference logits not found at {path}. "
            f"See docstring for generation instructions."
        )
    data = torch.load(path, weights_only=True)
    return data


@pytest.fixture(scope="module")
def compiled_model():
    """Compile (or load from cache) and load the model."""
    model = create_model(MODEL_PATH, COMPILED_MODEL_PATH)
    model.compile(compiled_model_path=COMPILED_MODEL_PATH)
    model.load(COMPILED_MODEL_PATH)
    return model


@pytest.fixture(scope="module")
def tokenizer():
    """Load tokenizer."""
    return AutoTokenizer.from_pretrained(MODEL_PATH)


@pytest.fixture(scope="module")
def generation_config(tokenizer):
    """Create generation config for logit validation."""
    return GenerationConfig(
        do_sample=False,
        max_new_tokens=NUM_TOKENS_TO_CHECK,
        eos_token_id=tokenizer.eos_token_id,
        pad_token_id=tokenizer.pad_token_id or tokenizer.eos_token_id,
    )


@pytest.fixture(scope="module")
def cpu_reference():
    """Load pre-computed CPU reference logits."""
    return load_cpu_reference_logits(CPU_REFERENCE_LOGITS_PATH)


def test_model_loads(compiled_model):
    """Test that model loads successfully (smoke test)."""
    assert compiled_model is not None
    assert hasattr(compiled_model, "config")
    print("PASS: Smoke test - Model loaded successfully")


def test_logit_accuracy(compiled_model, tokenizer, generation_config, cpu_reference):
    """
    Validate Neuron model logits against CPU HuggingFace reference.

    Uses pre-computed CPU reference logits and check_accuracy_logits_v2 which:
    - Wraps the Neuron model in HuggingFaceGenerationAdapter
    - Calls logit_validation with teacher forcing
    - Compares logits at multiple top-k tiers (top-5, top-50, top-1000, all)
    - Raises LogitMatchingValidationError on failure
    """
    expected_logits = cpu_reference["expected_logits"]
    input_ids = cpu_reference["input_ids"]
    attention_mask = torch.ones_like(input_ids)

    print(f"  Reference logits shape: {expected_logits.shape}")
    print(f"  Prompt: '{cpu_reference.get('prompt', 'N/A')}'")

    # check_accuracy_logits_v2 wraps the Neuron model in HuggingFaceGenerationAdapter
    # and runs logit_validation with teacher forcing against the reference logits.
    check_accuracy_logits_v2(
        neuron_model=compiled_model,
        expected_logits=expected_logits,
        inputs_input_ids=input_ids,
        inputs_attention_mask=attention_mask,
        generation_config=generation_config,
        num_tokens_to_check=NUM_TOKENS_TO_CHECK,
        divergence_difference_tol=DIVERGENCE_DIFFERENCE_TOL,
        tol_map=TOLERANCE_MAP,
        tokenizer=tokenizer,
    )

    print(f"PASS: Logit accuracy validated ({NUM_TOKENS_TO_CHECK} tokens)")


def test_performance_cte(compiled_model, tokenizer):
    """Measure CTE (prefill) latency."""
    prompt = "The capital of France is"
    input_ids = tokenizer(prompt, return_tensors="pt").input_ids
    seq_len = input_ids.shape[1]

    def run_cte():
        compiled_model.forward(
            input_ids=input_ids,
            attention_mask=torch.ones_like(input_ids),
            position_ids=torch.arange(seq_len, dtype=torch.int32).unsqueeze(0),
            seq_ids=torch.zeros(1, dtype=torch.int32),
        )

    # Warmup
    for _ in range(2):
        run_cte()

    # Measure
    times = []
    for _ in range(5):
        t0 = time.perf_counter()
        run_cte()
        times.append((time.perf_counter() - t0) * 1000)

    avg_ms = sum(times) / len(times)
    print(f"  CTE latency: {avg_ms:.1f} ms (avg of 5 runs)")
    # Sanity check: CTE should complete in under 2 seconds
    assert avg_ms < 2000, f"CTE too slow: {avg_ms:.1f} ms"
    print(f"PASS: CTE latency {avg_ms:.1f} ms")


def test_performance_tkg(compiled_model, tokenizer):
    """Measure TKG (decode) latency."""
    prompt = "The capital of France is"
    input_ids = tokenizer(prompt, return_tensors="pt").input_ids
    seq_len = input_ids.shape[1]

    # CTE first to set up KV cache
    output = compiled_model.forward(
        input_ids=input_ids,
        attention_mask=torch.ones_like(input_ids),
        position_ids=torch.arange(seq_len, dtype=torch.int32).unsqueeze(0),
        seq_ids=torch.zeros(1, dtype=torch.int32),
    )
    logits = (output.logits if hasattr(output, "logits") else output[0])[0, -1, :]
    prev_token = torch.argmax(logits.float().cpu()).item()
    cur_pos = seq_len

    def run_tkg(token_id, pos):
        return compiled_model.forward(
            input_ids=torch.tensor([[token_id]], dtype=torch.int64),
            attention_mask=torch.ones(1, pos + 1, dtype=torch.int64),
            position_ids=torch.tensor([[pos]], dtype=torch.int32),
            seq_ids=torch.zeros(1, dtype=torch.int32),
        )

    # Warmup TKG
    for i in range(3):
        out = run_tkg(prev_token, cur_pos + i)
        logits = (out.logits if hasattr(out, "logits") else out[0])[0, -1, :]
        prev_token = torch.argmax(logits.float().cpu()).item()

    cur_pos += 3

    # Measure
    times = []
    for i in range(10):
        t0 = time.perf_counter()
        out = run_tkg(prev_token, cur_pos + i)
        times.append((time.perf_counter() - t0) * 1000)
        logits = (out.logits if hasattr(out, "logits") else out[0])[0, -1, :]
        prev_token = torch.argmax(logits.float().cpu()).item()

    avg_ms = sum(times) / len(times)
    tok_per_sec = 1000 / avg_ms
    print(f"  TKG latency: {avg_ms:.1f} ms ({tok_per_sec:.1f} tok/s)")
    # Sanity check: TKG should complete in under 100 ms
    assert avg_ms < 100, f"TKG too slow: {avg_ms:.1f} ms"
    print(f"PASS: TKG latency {avg_ms:.1f} ms ({tok_per_sec:.1f} tok/s)")


if __name__ == "__main__":
    print("=" * 80)
    print("Solar Open 100B Integration Tests")
    print("=" * 80)

    # Load model
    print(f"\nLoading model from {MODEL_PATH}...")
    print(f"Compiled model path: {COMPILED_MODEL_PATH}")
    model = create_model(MODEL_PATH, COMPILED_MODEL_PATH)

    print("Compiling (may use cache)...")
    t0 = time.time()
    model.compile(compiled_model_path=COMPILED_MODEL_PATH)
    print(f"Compiled in {time.time() - t0:.0f}s")

    print("Loading weights...")
    t0 = time.time()
    model.load(COMPILED_MODEL_PATH)
    print(f"Loaded in {time.time() - t0:.0f}s")

    # Load tokenizer and configs
    tok = AutoTokenizer.from_pretrained(MODEL_PATH)
    gen_config = GenerationConfig(
        do_sample=False,
        max_new_tokens=NUM_TOKENS_TO_CHECK,
        eos_token_id=tok.eos_token_id,
        pad_token_id=tok.pad_token_id or tok.eos_token_id,
    )
    cpu_ref = load_cpu_reference_logits(CPU_REFERENCE_LOGITS_PATH)

    # Run tests
    print("\n" + "=" * 80)
    print("Running Tests")
    print("=" * 80)

    print("\n1. Smoke Test...")
    test_model_loads(model)

    print("\n2. Logit Accuracy Test (CPU reference vs Neuron)...")
    test_logit_accuracy(model, tok, gen_config, cpu_ref)

    print("\n3. CTE Performance Test...")
    test_performance_cte(model, tok)

    print("\n4. TKG Performance Test...")
    test_performance_tkg(model, tok)

    print("\n" + "=" * 80)
    print("All tests passed!")
    print("=" * 80)
